###############################################################################
#                          Generated on phpdocker.io                          #
###############################################################################
version: '3.1'
services:
  playground-mailhog:
    image: 'mailhog/mailhog:latest'
    container_name: playground-mailhog
    ports:
      - "8125:8025"

  playground-mysql:
    image: 'mysql:8.0'
    container_name: playground-mysql
    working_dir: /var/www/playground
    volumes:
        - ../mysql:/var/lib/mysql
        - ../mysql-files:/var/lib/mysql-files
        - ../cakephp:/var/www/playground
        - ./mysql/my.cnf:/etc/mysql/my.cnf
    ports:
      - "8106:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}

  playground-nginx:
    image: 'nginx:alpine'
    container_name: playground-nginx
    working_dir: /var/www/playground
    volumes:
        - ../cakephp:/var/www/playground
        - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
     - "8180:80"
    links:
     - playground-php-fpm

  playground-php-fpm:
    build: ./php-fpm
    container_name: playground-php-fpm
    working_dir: /var/www/playground
    volumes:
      - ../cakephp:/var/www/playground
      - ./php-fpm/php-ini-overrides.ini:/etc/php/7.4/fpm/conf.d/99-overrides.ini
    links:
      - playground-mailhog
      - playground-mysql
